// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAlz2fu3Km_rKmpLbnU1Hw4U6b9k13WJs',
    appId: '1:514791304480:web:2845cb20975c44110d3b45',
    messagingSenderId: '514791304480',
    projectId: 'spinafusion',
    authDomain: 'spinafusion.firebaseapp.com',
    storageBucket: 'spinafusion.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlf2wJ9JvTDZbC_b8gO8WAOI6Y_nFcIm0',
    appId: '1:514791304480:android:e420f3f9734de5ce0d3b45',
    messagingSenderId: '514791304480',
    projectId: 'spinafusion',
    storageBucket: 'spinafusion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL6NG1k_Ys7aTvETmJ557L24T4qeT0FP8',
    appId: '1:514791304480:ios:25542392b497cca50d3b45',
    messagingSenderId: '514791304480',
    projectId: 'spinafusion',
    storageBucket: 'spinafusion.firebasestorage.app',
    iosBundleId: 'com.example.spinAFusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL6NG1k_Ys7aTvETmJ557L24T4qeT0FP8',
    appId: '1:514791304480:ios:25542392b497cca50d3b45',
    messagingSenderId: '514791304480',
    projectId: 'spinafusion',
    storageBucket: 'spinafusion.firebasestorage.app',
    iosBundleId: 'com.example.spinAFusion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAlz2fu3Km_rKmpLbnU1Hw4U6b9k13WJs',
    appId: '1:514791304480:web:f3126659b4f428a40d3b45',
    messagingSenderId: '514791304480',
    projectId: 'spinafusion',
    authDomain: 'spinafusion.firebaseapp.com',
    storageBucket: 'spinafusion.firebasestorage.app',
  );
}
