import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'models/pokemon.dart';
import 'providers/providers.dart';
import 'screens/screens.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  await Hive.initFlutter();
  Hive.registerAdapter(PokemonAdapter());

  // borrar tot es hive
  // await Hive.deleteBoxFromDisk('pokedex');

  await Hive.openBox<Pokemon>('pokedex');

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => GameProvider()),
        ChangeNotifierProvider(create: (_) => PokedexProvider()),
        ChangeNotifierProvider(create: (_) => FusionCollectionProvider()),
        ChangeNotifierProxyProvider<GameProvider, HomeSlotsProvider>(
          create: (_) => HomeSlotsProvider(),
          update: (_, game, slots) {
            slots!.bindGameProvider(game);
            return slots;
          },
        ),
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      routes: {
        '/': (_) => const LoadingScreen(),
        '/home': (_) => const HomeScreen(),
      },
    );
  }
}
